// Copyright 2021-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= VK_EXT_timeline_semaphore_sync_fd
:toc: left
:refpage: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/
:sectnums:

This extension is intended to allow interaction between copy transference objects and timeline semaphores, especially exporting from timeline semaphores into syncFd objects.

== Problem Statement

Vulkan allows converting API sync objects from/to OS synchronization primitives in most of the cases. List of use-cases is long, including (but not limited to) OS-specific synchronization related to presentation.
This very useful feature is however mostly limited right now to legacy VkFences and binary VkSemaphores, as spec does not offer any way to provide value for timeline semaphore import/export operation.
Due to special nature of timeline semaphores, Vulkan specification currently does not define interactions between them and copy transference payload semaphores (like VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT).
However, at least for export part, it's easy to define operation that would create syncFd object from timeline semaphore object for provided value of the timeline semaphore, preserving copy transference semantics at the crucial level.

== Solution Space

Right now, the only way to get syncFd waiting for specific value of timeline semaphore is to create unsignalled syncFd, and wait for the timeline semaphore to reach selected value in separate thread, followed by sending the signal of syncFd.
This is of course neither elegant nor efficient solution.

The alternative is to allow to export syncFd from the vkGetSemaphoreFdKHR. This again can be done in a few ways, each of them requires changing specification language around limitations for the vkGetSemaphoreFdKHR and VkSemaphoreGetFdInfoKHR.
 . Define new function for obtaining syncFd from timeline semaphore. This is simple enought but stays in the opposition to past relationship between binary and timeline semaphores.
 . Extend VkSemaphoreGetFdInfoKHR pNext with a structure that would allow providing a value to wait for - and modify surroundign specification language to make it valid operation. This is the intended approach as it keeps current approach of timeline and binary semaphore being same VkSemaphore entity, while allowing effective operation of exporting timeline semaphore wait operation to syncFd.

== Proposal

This proposal is effectively defining new structure, that can expand VkSemaphoreGetFdInfoKHR pNext chain:

[source,c]
----
typedef struct VkTimelineSemaphoreSyncFdValueETC
{
    VkStructureType                     sType;
    const void*                         pNext;
    uint64_t                            value;
} VkTimelineSemaphoreSyncFdValueETX;
----

Requirements for valid usage with that structure would be:
 . VkSemaphore in parent VkSemaphoreGetFdInfoKHR has to be of VK_SEMAPHORE_TYPE_TIMELINE(_KHR) type.
 . If this pNext struct is present, requirements about copy transference from VkSemaphoreGetFdInfoKHR valid usage section are not being applied.

== Issues

=== PROPOSED: Should this extension contain paired functionality for importing syncFd into timeline semaphore?

This is intended to be out of the scope of this extension, unless there is strong pressure to have it included.

=== RESOLVED: What if timeline semaphore counter was already greater than value?

Signalled syncFd will be returned (-1).
