// Copyright 2021-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= VK_EXT_timeline_semaphore_sync_fd
:toc: left
:refpage: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/
:sectnums:

This extension is intended to allow interaction between copy transference objects and timeline semaphores, especially exporting from timeline semaphores into syncFd objects.

== Problem Statement

Vulkan allows converting API sync objects from/to OS synchronization primitives in most of the cases. List of use-cases is long, including (but not limited to) OS-specific synchronization related to presentation.
This very useful feature is however mostly limited right now to legacy VkFences and binary VkSemaphores, as spec does not offer any way to provide value for timeline semaphore import/export operation.
Due to special nature of timeline semaphores, Vulkan specification currently does not define interactions between them and copy transference payload semaphores (like VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT).
Copy transference export/import operation has a few characteristics - destination object of such operation is not aware of any other changes of the state of the source object, except the observed one,
any operation on the destination object has no effect on the source object - and in the case of export operation, the export operation itself behaves as a wait on the source object
(in case of binary semaphore effectively issuing a wait operation - and logical reset of the semaphore when this if signaled).
With the above, it's easy to define an export operation that would create a syncFd object from a timeline semaphore object for a provided value of the timeline semaphore, preserving copy transference semantics.
Exporting a semaphore to a syncFd has the same effect as waiting on the semaphore (and in case of timeline semaphore, a wait operation has no side effects) and does not take a reference to the semaphore payload.
Exported syncFd will be signaled only when the timeline semaphore reaches the value specified in the export operation.

== Solution Space

Right now, the only way to get a syncFd to wait for a specific value of timeline semaphore is to create an unsignaled syncFd, wait for the timeline semaphore to reach selected value in a separate thread, followed by sending the signaling the syncFd.
This is of course neither elegant nor efficient.

The alternative is to allow exporting syncFd from the link:{refpage}vkGetSemaphoreFdKHR.html[vkGetSemaphoreFdKHR]. This again can be done in a few ways, each of them requires changing specification language around limitations for the vkGetSemaphoreFdKHR and link:{refpage}VkSemaphoreGetFdInfoKHR.html[VkSemaphoreGetFdInfoKHR].

 . Define a new function for obtaining syncFd from timeline semaphore. This is simple but stays in the opposition to the existing relationship between binary and timeline semaphores.
 . Extend VkSemaphoreGetFdInfoKHR pNext with a structure that would allow providing a value to wait for - and modify surrounding specification language to make it a valid operation. This is the intended approach as it keeps the current approach of timeline and binary semaphore being the same VkSemaphore entity, while allowing effective operation of exporting timeline semaphore wait operation to syncFd.

== Proposal

This proposal is effectively defining new structure, that can expand VkSemaphoreGetFdInfoKHR pNext chain:

[source,c]
----
typedef struct VkTimelineSemaphoreSyncFdValueEXT
{
    VkStructureType                     sType;
    const void*                         pNext;
    uint64_t                            value;
} VkTimelineSemaphoreSyncFdValueEXT;
----

Requirements for valid usage with that structure would be:

 . VkSemaphore in parent VkSemaphoreGetFdInfoKHR has to be of VK_SEMAPHORE_TYPE_TIMELINE(_KHR) type.
 . If this pNext struct is present, requirements about copy transference from VkSemaphoreGetFdInfoKHR valid usage section are not being applied.

== Issues

=== PROPOSED: Should this extension contain paired functionality for importing syncFd into timeline semaphore?

This is intended to be out of the scope of this extension, unless there is strong reason to have it included.

=== RESOLVED: What if the timeline semaphore counter was already greater than value?

Signaled syncFd will be returned (-1).
